name: Rec Tv Kontrol

on:
  schedule:
    - cron: '0 */2 * * *'  
  workflow_dispatch:        

jobs:
  update-rectv:
    runs-on: ubuntu-latest

    permissions:
      contents: write  

    steps:
      - name: Repo'yu klonla
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }} 

      - name: Python kurulumu
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Gerekli paketleri yükle
        run: pip install requests cloudscraper

      

      - name: Rectv
        run: python rectv.py

      

          - name: Değişiklik Kontrolü
        id: degisiklik_kontrol
        run: |
          git diff --quiet . || echo "degisiklik=true" >> $GITHUB_OUTPUT
          
      - name: Değişiklikleri Commit Et
        if: steps.degisiklik_kontrol.outputs.degisiklik == 'true'
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m " Kanallar/kerim.m3u güncellendi - $(date +'%Y-%m-%d %H:%M:%S')"
          git push
